name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        poetry-version: [1.1.10]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "README.md, setup.py, poetry.lock, pyproject.toml"
          allow_failure: true
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Check Python version
        run: poetry run python --version
      - name: Check formatting
        run: poetry run black --check .
